spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sun_dev
    username: sun_dev_user
    password: sun
    initialization-mode: never
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: sun_database_create.sql