version: 2.1

orbs:
  maven: circleci/maven@1.1

workflows:
  maven_test:
    jobs:
      - maven/test
      # run tests! and gen code coverage
      - run: mvn integration-test cobertura:cobertura

      - store_test_results:
          path: target/surefire-reports

      - run:
          name: Send to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
